# Generated by Django 4.1.7 on 2023-03-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo_model',
        ),
    ]
