# Generated by Django 4.1.7 on 2023-03-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demo_app', '0002_delete_demo_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=128)),
                ('object', models.CharField(max_length=512)),
                ('app_name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
